### ISSUE TITLE
scrapy screen shot 01

### ISSUE THREAD

**Issue by runningabcd** [xiaozhaorunning/Spider-Life#1]

**Comment by xiaozhaorunning** [comment]
<img width="1317" alt="main" src="https://user-images.githubusercontent.com/8281035/49266403-108e5a00-f491-11e8-856d-faee4014939e.png">

**Comment by xiaozhaorunning** [comment]
![image](https://user-images.githubusercontent.com/8281035/49267171-1e91aa00-f494-11e8-988f-f1164b2e9b22.png)

![image](https://user-images.githubusercontent.com/8281035/49267196-4123c300-f494-11e8-9ef1-3b9ccfa0b014.png)

![image](https://user-images.githubusercontent.com/8281035/49267244-70d2cb00-f494-11e8-8a33-37d53c179583.png)

**Comment by runningabcd** [comment]
![image](https://user-images.githubusercontent.com/8281035/49370000-d5f51d80-f72d-11e8-8b22-8785ba2a8456.png)
![image](https://user-images.githubusercontent.com/8281035/49370060-0b9a0680-f72e-11e8-9446-71943441a8cb.png)

**Comment by runningabcd** [comment]
![image](https://user-images.githubusercontent.com/8281035/49720891-dc3e4900-fc9b-11e8-9b01-27c897279b5b.png)
![image](https://user-images.githubusercontent.com/8281035/49720894-dea0a300-fc9b-11e8-862d-da57334c2ca0.png)
